- name: ansible
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    - name: add docker-compose.yml
      command: touch docker-compose.yml

    - name: fill docker-compose.yml
      command: echo -e "version: '3.3'\n\nservices:\n   wordpress:\n     image: wordpress:latest\n     ports:\n       - "80:80"\n     restart: always" >> docker-compose.yml

    - name: Docker-compose up
      command: docker-compose up -d

    - name: Open container
      command: docker exec -it wordpresswithrds_wordpress_1 bash -c wordpresswithrds_wordpress_1 < ExtraCode/docker.sh
      
