name: 'Ansible'

on:
  workflow_run:
    workflows:
      - MySQL
    types: 
      - completed
    branches:
      - main
    
jobs:
  mysql:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITTOKEN}}
          workflow: terraform.yml
          workflow_conclusion: success
          name: output
          repo: KirillSSS/Infrastructure_As_Code

      - id: host
        env:
          SSH: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            host=$(grep "ec2_endpoint" output.log | awk -F  ":" '{print $1}' )
            host=${host//'ec2_endpoint = "'}
            host=${host//'"'}
            echo $host >> ExtraCode/hosts
            echo "$SSH" > ExtraCode/key.pem
            chmod 400 ExtraCode/key.pem
            cat ExtraCode/key.pem
      - name: Ansible
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: 'ExtraCode/git.yml'
          inventoryFile: 'ExtraCode/hosts'
          keyFile: 'ExtraCode/key.pem'

      - id: host
        env:
          SSH: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            host=$(grep "ec2_endpoint" output.log | awk -F  ":" '{print $1}' )
            host=${host//'ec2_endpoint = "'}
            host=${host//'"'}
            echo $host >> ExtraCode/hosts
            echo "$SSH" > ExtraCode/key.pem
            chmod 400 ExtraCode/key.pem
            cat ExtraCode/key.pem
      - name: Ansible
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: 'ExtraCode/ansible.yml'
          inventoryFile: 'ExtraCode/hosts'
          keyFile: 'ExtraCode/key.pem'