name: 'MySQL'

on:
  workflow_dispatch:
    inputs:
      logLevel:     
        required: true
        default: 'warning'
      tags:
        description: 'MySQL Import dump'  
    
jobs:
  mysql:
    name: 'MySQL'
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITTOKEN}}
          workflow: terraform.yml
          workflow_conclusion: success
          name: output

      - shell: bash
        run: |
          db=$(cat output.log | grep -w rds_endpoint)
          db=$(grep "rds_endpoint" output.log | awk -F  ":" '{print $1}' )
          db=${db//'rds_endpoint = "'}
          echo $db
          mysql --host $db --port 3306 -uadmin -pq1q1q1q1 aws-database < ExtraCode/mysql.sql